# Generated by Django 5.1 on 2025-01-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_appointment_options_workinghours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name': 'Working hour', 'verbose_name_plural': 'Working hours'},
        ),
    ]
