# Generated by Django 5.1 on 2025-01-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_appointment_options_alter_workinghours_options'),
        ('doctor', '0007_alter_appointment_options_alter_workinghours_options_and_more'),
    ]

    operations = [
    ]
